Footer
Natallia-Yarashevich/Olga-psychologist pull request #5
Opened 2023-04-18 20:28 UTC by your-m1nd

update blog and footer

2023-04-18 20:56 UTC, Natallia-Yarashevich requested changes
пересмотреть стиль  subtitle

2023-04-19 07:00 UTC, Natallia-Yarashevich reviewed
Все отлично

2023-04-19 09:56 UTC, valeryshel approved these changes

2023-04-19 09:56 UTC, valeryshel approved these changes

2023-04-19 10:20 UTC, Natallia-Yarashevich approved these changes

2023-04-19 11:55 UTC, Natallia-Yarashevich approved these changes

2023-04-19 11:56 UTC, merged